name: Run all tests on Windows, macOS and Ubuntu x Firefox, WebKit and Chromium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # https://playwright.dev/docs/ci-intro
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run all tests
        run: npm run tests:all
